name: Snyk Security Check for New Vulnerabilities

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Install Snyk and snyk-delta
        run: |
          npm install -g snyk
          npm install -g snyk-delta

      - name: Run Snyk to check for new vulnerabilities
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: |
          # Step 1: Test PR code
          snyk test --all-projects --severity-threshold=high --json-file-output=snyk-results.json || true

          # Step 2: Check for vulnerabilities in delta 
          cat snyk-results.json | snyk-delta --baselineOrg ${{ secrets.SNYK_ORG_ID }} --fail-on-new
